// import { MyError } from '../shared/error.js';
// import type { ApplicationServerRequest, ApplicationServerResponse } from '../shared/server-helper-hmr.js';
// import { ParameterValidator } from '../shared/server-helper-hmr.js';

// the most minimal api demo that don't use codegen and even don't use akari

// TODO too many redundant validations generated by ai,
// they are handled in parametervalidator utility, remove them if you want to make this more formal

// { userId, id, name }
const sessions = [];
// { userId, id, content, sessionId }
const messages = [];

// Helper function to generate unique IDs
function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).substr(2);
}

// Helper function to find session and check ownership
function findUserSession(userId, sessionId) {
  return sessions.find(s => s.userId === userId && s.id === sessionId);
}

// Helper function to find message and check ownership
function findUserMessage(userId, messageId, sessionId) {
  return messages.find(m => 
    m.userId === userId && 
    m.id === messageId && 
    m.sessionId === sessionId
  );
}

// Get all sessions for the authenticated user
function getSessions(ax) {
  const userId = ax.userId;  
  const userSessions = sessions.filter(s => s.userId === userId);
  return userSessions;
}

// Get a specific session by ID
function getSession(ax, sessionId) {
  const userId = ax.userId;
  if (!sessionId) {
    return { error: "Session ID is required", status: 400 };
  }
  
  const session = findUserSession(userId, sessionId);
  if (!session) {
    return { error: "Session not found", status: 404 };
  }
  
  // Get messages for this session
  const sessionMessages = messages.filter(m => 
    m.userId === userId && m.sessionId === sessionId
  );
  
  return {
    ...session,
    messages: sessionMessages
};
}

// Create a new session
function addSession(ax, body) {
  const userId = ax.userId;  
  if (!body || !body.name) {
    return { error: "Session name is required", status: 400 };
  }
  
  const newSession = {
    userId,
    id: generateId(),
    name: body.name.trim()
  };
  
  sessions.push(newSession);
  
  return newSession;
}

// Update an existing session
function updateSession(ax, body) {
  const userId = ax.userId;  
  if (!body || !body.id || !body.name) {
    return { error: "Session ID and name are required", status: 400 };
  }
  
  const session = findUserSession(userId, body.id);
  if (!session) {
    return { error: "Session not found or access denied", status: 404 };
  }
  
  session.name = body.name.trim();
  return session;
}

// Delete a session and all its messages
function removeSession(ax, sessionId) {
  const userId = ax.userId;  
  if (!sessionId) {
    return { error: "Session ID is required", status: 400 };
  }
  
  const sessionIndex = sessions.findIndex(s => s.userId === userId && s.id === sessionId);
  if (sessionIndex === -1) {
    return { error: "Session not found or access denied", status: 404 };
  }
  
  // Remove the session
  sessions.splice(sessionIndex, 1);
  
  // Remove all messages associated with this session
  const messageIndices = [];
  messages.forEach((m, index) => {
    if (m.userId === userId && m.sessionId === sessionId) {
      messageIndices.push(index);
    }
  });
  
  // Remove from end to start to avoid index shifting issues
  for (let i = messageIndices.length - 1; i >= 0; i--) {
    messages.splice(messageIndices[i], 1);
  }
}

// Add a message to a specific session
function addMessage(ax, sessionId, body) {
  const userId = ax.userId;
  
  if (!sessionId) {
    return { error: "Session ID is required", status: 400 };
  }
  if (!body || !body.content) {
    return { error: "Message content is required", status: 400 };
  }
  
  // Verify session exists and belongs to user
  const session = findUserSession(userId, sessionId);
  if (!session) {
    return { error: "Session not found or access denied", status: 404 };
  }
  
  const newMessage = {
    userId,
    id: generateId(),
    content: body.content.trim(),
    sessionId
  };
  
  messages.push(newMessage);
  
  return newMessage;
}

// Update an existing message
function updateMessage(ax, sessionId, body) {
  const userId = ax.userId;

  if (!sessionId) {
    return { error: "Session ID is required", status: 400 };
  }
  
  if (!body || !body.id || !body.content) {
    return { error: "Message ID and content are required", status: 400 };
  }
  
  // Verify session exists and belongs to user
  const session = findUserSession(userId, sessionId);
  if (!session) {
    return { error: "Session not found or access denied", status: 404 };
  }
  
  const message = findUserMessage(userId, body.id, sessionId);
  if (!message) {
    return { error: "Message not found or access denied", status: 404 };
  }
  
  message.content = body.content.trim();
  
  return message;
}

// AI generates these test cases, consider change them to client side test cases
function runTests() {
  // Mock user context
  const user1 = { userId: "user123" };
  const user2 = { userId: "user456" };
  
  console.log("=== Testing Session CRUD ===");
  
  // Create sessions for user1
  const session1 = addSession(user1, { name: "Chat about JavaScript" });
  console.log("Created session:", session1);
  
  const session2 = addSession(user1, { name: "Project Discussion" });
  console.log("Created session:", session2);
  
  // Create session for user2 (should be isolated)
  addSession(user2, { name: "User2 Session" });
  
  // Get all sessions for user1
  const allSessions = getSessions(user1);
  console.log("User1 sessions:", allSessions);
  
  // Get specific session
  const singleSession = getSession(user1, session1.data.id);
  console.log("Single session with messages:", singleSession);
  
  // Update session
  const updated = updateSession(user1, { 
    id: session1.data.id, 
    name: "Advanced JavaScript Chat" 
  });
  console.log("Updated session:", updated);
  
  console.log("\n=== Testing Message CRUD ===");
  
  // Add messages to session1
  const msg1 = addMessage(user1, session1.data.id, { content: "Hello, how does closure work?" });
  console.log("Added message:", msg1);
  
  const msg2 = addMessage(user1, session1.data.id, { content: "Can you explain promises?" });
  console.log("Added message:", msg2);
  
  // Add message to session2
  addMessage(user1, session2.data.id, { content: "When is the deadline?" });
  
  // Get session with messages
  const sessionWithMessages = getSession(user1, session1.data.id);
  console.log("Session with messages:", sessionWithMessages);
  
  // Update a message
  const updatedMsg = updateMessage(user1, session1.data.id, {
    id: msg1.data.id,
    content: "How do JavaScript closures work in detail?"
  });
  console.log("Updated message:", updatedMsg);
  
  // Try to access another user's session (should fail)
  const unauthorizedAccess = getSession(user2, session1.data.id);
  console.log("Unauthorized access attempt:", unauthorizedAccess);
  
  console.log("\n=== Testing Deletion ===");
  
  // Delete session (should also delete its messages)
  const deletion = removeSession(user1, session1.data.id);
  console.log("Delete session result:", deletion);
  
  // Verify session is gone
  const deletedSession = getSession(user1, session1.data.id);
  console.log("Deleted session access:", deletedSession);
  
  // Verify messages are gone
  const remainingMessages = messages.filter(m => m.sessionId === session1.data.id);
  console.log("Remaining messages for deleted session:", remainingMessages);
}

// pretend they are imported
class MyError extends Error {
    constructor(kind, message, additionalInfo) { super(message); this.kind = kind; this.name = 'MyError'; this.additionalInfo = additionalInfo; }
}
class ParameterValidator {
    constructor(parameters) { this.parameters = parameters; }
    validate(name, optional, convert, validate) {
        if (!this.parameters.has(name)) {
            if (optional) { return null; } else { throw new MyError('common', `missing required parameter ${name}`); }
        }
        const raw = this.parameters.get(name);
        const result = convert(raw);
        if (validate(result)) { return result; } else { throw new MyError('common', `invalid parameter ${name} value ${raw}`); }
    }
    id(name) { return this.validate(name, false, parseInt, v => !isNaN(v) && v > 0); }
    idopt(name) { return this.validate(name, true, parseInt, v => !isNaN(v) && v > 0); }
    string(name) { return this.validate(name, false, v => v, v => !!v); }
}
export async function dispatch(request) {
    const v = new ParameterValidator(new URLSearchParams(request.query));
    const ax = { time: request.time, userId: request.userId };
    const action = {
        'GET /v1/sessions': () => getSessions(ax),
        'GET /v1/session': () => getSession(ax, v.id('sessionId')),
        // 'GET /public/v1/session': () => publicGetSession(ax, v.string('shareId')),
        'PUT /v1/add-session': () => addSession(ax, request.body),
        'POST /v1/update-session': () => updateSession(ax, request.body),
        'DELETE /v1/remove-session': () => removeSession(ax, v.id('sessionId')),
        'PUT /v1/add-message': () => addMessage(ax, v.id('sessionId'), request.body),
        'POST /v1/update-message': () => updateMessage(ax, v.id('sessionId'), request.body),
    }[`${request.method} ${request.path}`];
    return action ? { body: await action() } : { error: new MyError('not-found', 'action not found') };
}

// TODO start a service if run this script run alone, testing ipc communication
if (import.meta.main) {

}
