// ATTENTION: 
// This code was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

import type { Context } from '../../shared/types/api';
import type { Value1 } from '../api';

export async function getValue1s(ctx: Context): Promise<Value1[]> {
    return [];
}

export async function getValue1(ctx: Context, valueId: number): Promise<Value1> {
    return { name: 'name' };
}
