// ATTENTION: 
// This code was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

import { WebContext, validateId, validateBody } from '../../shared/api-server';
import { MyError } from '../../shared/error';
import { getChanges, getChange, createChange, updateChange, deleteChange } from './default';

export async function dispatch(ctx: WebContext) {
    let match: RegExpExecArray;
    const methodAndPath = `${ctx.method} ${ctx.path}`; // method and path, note that query is not in ctx.path

    match = /GET \/changes/.exec(methodAndPath);
    if (match) {
        ctx.body = await getChanges(ctx.state);
        return;
    }

    match = /GET \/changes\/(?<changeId>\d+)/.exec(methodAndPath);
    if (match) {
        ctx.body = await getChange(ctx.state, validateId('changeId', match.groups['changeId']));
        return;
    }

    match = /POST \/changes\/(?<changeId>\d+)/.exec(methodAndPath);
    if (match) {
        ctx.body = await createChange(ctx.state, validateId('changeId', match.groups['changeId']), validateBody(ctx.body));
        ctx.status = 201;
        return;
    }

    match = /PUT \/changes\/(?<changeId>\d+)/.exec(methodAndPath);
    if (match) {
        ctx.body = await updateChange(ctx.state, validateId('changeId', match.groups['changeId']), validateBody(ctx.body));
        return;
    }

    match = /DELETE \/changes\/(?<changeId>\d+)/.exec(methodAndPath);
    if (match) {
        await deleteChange(ctx.state, validateId('changeId', match.groups['changeId']));
        ctx.status = 204;
        return;
    }

    throw new MyError('not-found', `invalid invocation`);
}
