#!/usr/bin/env node
Object.defineProperty(exports, "__esModule", { value: true });
const admin_base_1 = require("./script/bin/admin-base");
const build_self_1 = require("./script/bin/build-self");
const build_server_core_1 = require("./script/bin/build-server-core");
const build_home_page_1 = require("./script/bin/build-home-page");
const argv = process.argv.slice(2);
if (argv[0] == 'self') {
    build_self_1.build();
}
else if (argv[0] == 'server-core') {
    build_server_core_1.build(false);
}
else if (argv[0] == 'watch' && argv[1] == 'server-core') {
    build_server_core_1.build(true);
}
else if (argv[0] == 'home-page') {
    build_home_page_1.build(false);
}
else if (argv[0] == 'watch' && argv[1] == 'home-page') {
    build_home_page_1.build(true);
}
else if (argv[0] == 'shutdown') {
    admin_base_1.send({ type: 'shutdown' }).then(() => process.exit(0));
}
else if (argv[0] == 'content-update' && argv.length == 3) {
    admin_base_1.send({ type: 'content-update', parameter: { app: argv[1], name: argv[2] } }).then(() => process.exit(0));
}
else {
    console.log('unknown command.');
}
