#!/usr/bin/env zsh

if (( # != 2 )); then
    echo build-client: require exactly 2 arguments
    exit 1
fi

if [[ $2 == dev ]]; then

    echo "> webpack --env.project_name=$1 --display minimal --mode development"
    webpack --env.project_name=$1 --display minimal --mode development
    exit $?
fi
if [[ $2 == pro ]]; then
    
    echo "> webpack --env.project_name=$1 --display minimal --mode development"
    webpack --env.project_name=$1 --display minimal --mode production
    exit $?
fi

echo build-client: parameter 2 must be dev/pro
exit 1

