// ATTENTION: 
// This code was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

import { MyFetch } from '../../shared/myfetch';
import type { Value1 } from '../api';

const myfetch = new MyFetch('cost');

export const getValue1s = (): Promise<Value1[]> => myfetch.get('/value1s');
export const getValue1 = (valueId: number): Promise<Value1> => myfetch.get(`/value1/${valueId}`);
