// ATTENTION: 
// This code was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

import * as myfetch from '../../shared/api-client';
import type { Change } from '../api';

export const getChanges = (): Promise<Change[]> => myfetch.get('/value1s');
export const getChange = (changeId: number): Promise<Change> => myfetch.get(`/value1/${changeId}`);
