database:
  host: /run/pgsql
  port: 5432
  user: fine
  password:
  database: fine

applications:
  app1:
    # use fixed app.example.com to host the app at app.example.com/{appname}/
    host: app.example.com
    module: ./servers/app1.js
  app3:
    # or use other subdomain to host the service, subdomain may not be same as service name
    host: app3coolsubdomain.example.com
    socket: /etc/app3/app3.socket
