# databases to backup
databases:
  # username:database
  - fine:fine

aliyunoss:
  region: cn-shanghai
  # is internal access
  internal: true
  bucket: backup
  access-key-id:
  access-key-secret:
  # sub path to put the files, if provided should be absolute
  path:
