# why is this toml but others are yaml?
# because toml is popular in rust and have builtin support in python

# oss configs
region = "cn-shanghai"
internal = true
bucket = "backup"
access-key-id = ""
access-key-secret = ""
