
# CONNECTIONS AND AUTHENTICATION
# disable TCP connection
listen_addresses = ''
# change to non default port value
port = 6543
# change to not /tmp for volume mapping
unix_socket_directories = '/run/pgsql'

# WRITE AHEAD LOG
# no need replica
wal_level = minimal
# disable replica
max_wal_senders = 0
# reduce disk usage
wal_compression = zstd

# REPORTING AND LOGGING
# log into ~ but not ~/data to allow volume mapping separately
log_directory = '/var/lib/pgsql/logs'
# add csvlog
log_destination = 'stderr, csvlog'
# csvlog need this
logging_collector = on
# more consistent with existing name pattern in this project
log_filename = 'postgresql-%y%m%d.log'
# see long running statements
log_min_duration_statement = 250ms
# log connections
log_connections = 'authorization, setup_durations'
# and disconnections
log_disconnections = on
