name: fine

services:
  # docker compose up -d acme
  # or run shell: docker compose run --rm --name acme-shell1 --entrypoint sh acme
  #   # docker compose run does not respect container_name if you ask
  #   - initial setup: /create.py
  #   - or restore backup: tar xJf letsencrypt-backup.tar.xz -C /
  #   - update certificate domains or other certbot commands: certbot certonly ...
  #   - check renew schedule: cat /etc/letsencrypt/renewal-schedule/next
  acme:
    image: my/certbot:1
    container_name: acme1
    environment:
      # make absolute paths more centralized
      FINE_CONFIG_DIR: /etc/fine
      FINE_SOCKET_DIR: /run/fine
    volumes:
      - certificates:/etc/letsencrypt
      # why do you need to map this?
      - certbot-libs:/var/lib/letsencrypt
      - certbot-logs:/var/log/letsencrypt
      # socket dir can work with ro
      - fine-sockets:/run/fine:ro
      - type: volume
        source: fine-configs
        target: /etc/fine/certbot.yml
        volume: { subpath: certbot.yml }
        read_only: true
      - type: volume
        source: fine-configs
        target: /etc/fine/domains.yml
        volume: { subpath: domains.yml }
        read_only: true

  # docker compose up -d database
  # or run shell: docker compose run --rm --name database-shell1 --entrypoint sh database
  #   - initial setup: ./initdb.sh
  # or directly psql: docker compose run --rm --name database-shell1 --entrypoint psql database
  database:
    image: my/postgres:1
    container_name: database1
    stop_grace_period: 5m # why can't I write 5min for 5 minutes
    volumes:
      - database:/var/lib/pgsql
      - database-logs:/var/lib/pgsql/logs
      - database-sockets:/run/pgsql

  # docker compose run --rm --name akari1 -v .:/self -p 8001:8001 akari
  #   # docker compose run does not respect port, if you ask
  #   # port and container_name is skipped in run because they may be conflict with existing up'd containers
  # or run shell: docker compose run --rm --name akari2 -v .:/self --entrypoint sh akari
  akari:
    image: node
    # assign a special profile so this is excluded in docker compose up (without service name and profile),
    # you mean this is even excluded in docker compose config? and only appears in docker compose --profile akari config
    profiles: [akari]
    working_dir: /var/fine
    entrypoint: node akari.ts
    environment:
      # inline host in ps1 so that you don't need to specify host
      PS1: '[@AKARI-SHELL:\w]\n\$ '
      # make absolute paths more centralized
      FINE_CONFIG_DIR: /etc/fine
    # the volume list is same as main service, but most of them are not readonly
    volumes:
      - fine-program:/var/fine
      - node_modules:/var/fine/node_modules:ro
      - fine-configs:/etc/fine
      - fine-sockets:/run/fine:ro
      - fine-logs:/var/log/fine:ro
      - certificates:/etc/letsencrypt:ro
      - fine-public:/var/fine/public
      - database-logs:/var/lib/pgsql/logs:ro
      - certbot-logs:/var/log/letsencrypt:ro

  # docker compose up -d web
  # restart: docker compose restart web
  web:
    image: node
    container_name: fine1
    working_dir: /var/fine
    entrypoint: node index.js
    environment:
      # make absolute paths more centralized
      FINE_WEBROOT: /var/fine
      FINE_LOGS_DIR: /var/log/fine
      FINE_SOCKET_DIR: /run/fine
      FINE_CONFIG_DIR: /etc/fine
    ports:
      - 80:80
      - 443:443
    volumes:
      - fine-program:/var/fine:ro
      # this seems work, if some error happens, remove ro
      - node_modules:/var/fine/node_modules:ro
      - fine-sockets:/run/fine
      - fine-logs:/var/log/fine
      - database-sockets:/run/pgsql:ro
      - certificates:/etc/letsencrypt:ro
      - fine-public:/var/fine/public:ro
      - type: volume
        source: fine-configs
        target: /etc/fine/access.yml
        volume: { subpath: access.yml }
        read_only: true
      - type: volume
        source: fine-configs
        target: /etc/fine/content.yml
        volume: { subpath: content.yml }
        read_only: true
      - type: volume
        source: fine-configs
        target: /etc/fine/domains.yml
        volume: { subpath: domains.yml }
        read_only: true
      # NOTE hmr servers need their config files manually add here, is this good?
      - type: volume
        source: fine-configs
        target: /etc/fine/short-link.yml
        volume: { subpath: short-link.yml }
        read_only: true
    # main program does not depend on database running (serve static contents)
    # main program does not depend on certificate renewer running (only depend on file exists)

  # docker compose up -d backup
  # or run shell: docker compose run --rm --name backup2 --entrypoint sh backup
  # or cat: docker run -it --rm --name helper1 -v fine-backup-logs:/data/backup-logs alpine cat /data/backup-logs/backup-20260418-130228.log
  backup:
    image: my/fine-backup:1
    container_name: backup1
    working_dir: /work
    environment:
      # make absolute paths more centralized
      FINE_CONFIG_DIR: /etc/fine
      BACKUP_LOGS_DIR: /data/backup-logs
    volumes:
      - type: volume
        source: fine-configs
        target: /etc/fine/backup.yml
        volume: { subpath: backup.yml }
        read_only: true
      - node_modules:/work/node_modules:ro
      - certificates:/data/certificates:ro
      - fine-configs:/data/configs:ro
      - fine-program:/data/program:ro
      # you may map them into another folder
      # for more precise management, for now simply bundle them together
      - certbot-logs:/data/certbot-logs:ro
      - database-logs:/data/database-logs:ro
      - fine-logs:/data/fine-logs:ro
      # every backup operation backups previous backup logs?
      - backup-logs:/data/backup-logs
      - database-sockets:/run/pgsql:ro

volumes:
  database:
    name: fine-database
  database-logs:
    name: fine-database-logs
  database-sockets:
    name: fine-database-sockets
  certificates:
    name: certificates
  certbot-libs:
    name: certbot-libs
  certbot-logs:
    name: certbot-logs
  fine-configs:
    name: fine-configs
  fine-sockets: # this is only for sockets, but you cannot share tmpfs accross containers
    name: fine-sockets
  fine-logs:
    name: fine-logs
  fine-program:
    name: fine-program
  fine-public: # should be easier to mount and manipulate
    name: fine-public
  node_modules:
    name: fine-node_modules
  backup-logs:
    name: fine-backup-logs

networks:
  default:
    name: fine1
    enable_ipv6: true
