name: fine

services:
  # docker compose up -d acme
  # or run shell: docker compose run --rm --name acme-shell1 -e "PS1=[@ACME-SHELL:\w]\n\$ " --entrypoint sh acme
  #   - initial setup: /create.py
  #   - or restore backup: tar xJf letsencrypt-backup.tar.xz -C /
  #   - update certificate domains or other certbot commands: certbot certonly ...
  #   - check renew schedule: cat /etc/letsencrypt/renewal-schedule/next
  acme:
    image: fine/certbot
    container_name: acme1
    environment:
      # make absolute paths more centralized
      FINE_CONFIG_DIR: /etc/fine
      FINE_SOCKET_DIR: /run/fine
    volumes:
      - certificates:/etc/letsencrypt
      # why do you need to map this?
      - certbot-libs:/var/lib/letsencrypt
      - certbot-logs:/var/log/letsencrypt
      # socket dir can work with ro
      - fine-sockets:/run/fine:ro
      - type: volume
        source: fine-configs
        target: /etc/fine/certbot.yml
        volume: { subpath: certbot.yml }
        read_only: true
      - type: volume
        source: fine-configs
        target: /etc/fine/domains.yml
        volume: { subpath: domains.yml }
        read_only: true

  # docker compose up -d database
  # or run shell: docker compose run --rm --name db-shell1 -e "PS1=[@PG-SHELL:\w]\n\$ " --entrypoint sh database
  #   - prepare initial data in database-backup and run initial setup: ./setup.sh
  # or directly psql: docker compose run --rm --name psql1 --entrypoint "psql fine fine" database
  # or run backup.sh: docker compose run --rm --name db-backup1 --entrypoint backup.sh database
  database:
    image: fine/database
    container_name: database1
    stop_grace_period: 5m # why can't I write 5min for 5 minutes
    volumes:
      - database:/var/lib/pgsql
      - database-logs:/var/lib/pgsql/logs
      - database-backup:/var/lib/pgsql/backup
      - database-sockets:/run/pgsql

  # docker compose run --rm --name akari1 -v .:/self -p 8001:8001 akari
  #   # docker compose run does not respect port, if you ask
  #   # port and container_name is skipped in run because they may be conflict with existing up'd containers
  # or run shell: docker compose run --rm --name akari2 -v .:/self --entrypoint sh akari
  akari:
    # fine/node is official node if you ask, use this naming convention is for convenience in backup script
    image: fine/node
    # assign a special profile so this is excluded in docker compose up (without service name and profile),
    # you mean this is even excluded in docker compose config? and only appears in docker compose --profile akari config
    profiles: [akari]
    working_dir: /var/www
    entrypoint: node akari.ts
    environment:
      # inline host in ps1 so that you don't need to specify host
      PS1: '[@AKARI-SHELL:\w]\n\$ '
      # make absolute paths more centralized
      FINE_CONFIG_DIR: /etc/fine
    # the volume list is same as main service, but most of them are not readonly
    volumes:
      - fine-program:/var/www
      - fine-public:/var/www/public
      - fine-configs:/etc/fine
      - fine-sockets:/run/fine:ro
      - fine-logs:/var/log/fine:ro
      - certificates:/etc/letsencrypt:ro
      - database-logs:/var/lib/pgsql/logs:ro
      - certbot-logs:/var/log/letsencrypt:ro
      - backup-logs:/var/log/backup:ro

  # docker compose up -d web
  # restart: docker compose restart web
  web:
    # fine/node is official node if you ask, use this naming convention is for convenience in backup script
    image: fine/node
    container_name: fine1
    working_dir: /var/www
    entrypoint: node index.js
    environment:
      # make absolute paths more centralized
      FINE_WEBROOT: /var/www
      FINE_LOGS_DIR: /var/log/fine
      FINE_SOCKET_DIR: /run/fine
      FINE_CONFIG_DIR: /etc/fine
      FINE_DEBUG: 1 # use this to enable debug log
    ports:
      - 80:80
      - 443:443
    volumes:
      # :ro seems ok, if some error happens, remove ro
      - fine-program:/var/www:ro
      - fine-public:/var/www/public:ro
      - fine-sockets:/run/fine
      - fine-logs:/var/log/fine
      - database-sockets:/run/pgsql:ro
      - certificates:/etc/letsencrypt:ro
      - type: volume
        source: fine-configs
        target: /etc/fine/access.yml
        volume: { subpath: access.yml }
        read_only: true
      - type: volume
        source: fine-configs
        target: /etc/fine/content.yml
        volume: { subpath: content.yml }
        read_only: true
      - type: volume
        source: fine-configs
        target: /etc/fine/domains.yml
        volume: { subpath: domains.yml }
        read_only: true
      - type: volume
        source: fine-configs
        target: /etc/fine/dontry.yml
        volume: { subpath: dontry.yml }
        read_only: true
      # NOTE hmr servers need their config files manually add here, is this good?
      - type: volume
        source: fine-configs
        target: /etc/fine/short-link.yml
        volume: { subpath: short-link.yml }
        read_only: true
    # main program does not depend on database running (serve static contents)
    # main program does not depend on certificate renewer running (only depend on file exists)

  # run backup.py: docker compose run --rm --name backup1 -v .:/work --entrypoint "python /work/backup.py" backup
  backup:
    # fine/python is official python if you ask, use this naming convention is for convenience in backup script
    image: fine/python
    # assign a special profile so this is excluded in docker compose up (without service name and profile)
    profiles: [backup]
    # for now do not make absolute paths more centralized like other containers,
    # a lot of paths are used in backup-schedule.py and they are already centralized,
    # turn them into environment variables is not meaningful
    # environment:
    volumes:
      # fine-configs:/etc/fine # no need to map config twice
      # program.tar.xz
      # # cannot use this
      # - fine-program:/data/program:ro
      # - fine-configs:/data/program/config:ro
      # - certificates:/data/program/certificates:ro
      - fine-program:/data/main/program:ro
      - fine-configs:/data/main/configs:ro
      - certificates:/data/main/certificates:ro
      # database.tar.xz
      - database-backup:/data/base:ro
      # logs.tar.xz
      - fine-logs:/data/logs/fine:ro
      - database-logs:/data/logs/database:ro
      - certbot-logs:/data/certbot-logs-staging:ro # not this: certbot-logs:/data/logs/certbot:ro
      # public.tar.xz
      - fine-public:/data/public:ro

volumes:
  database:
    name: fine-database
  database-logs:
    name: fine-database-logs
  database-backup:
    name: fine-database-backup
  database-sockets:
    name: fine-database-sockets
  certificates:
    name: certificates
  certbot-libs:
    name: certbot-libs
  certbot-logs:
    name: certbot-logs
  fine-configs:
    name: fine-configs
  fine-sockets: # this is only for sockets, but you cannot share tmpfs accross containers
    name: fine-sockets
  fine-logs:
    name: fine-logs
  fine-program:
    name: fine-program
  fine-public: # should be easier to mount and manipulate
    name: fine-public
  backup-logs:
    name: fine-backup-logs

networks:
  default:
    name: fine1
    enable_ipv6: true
