# TYPE  DATABASE        USER            ADDRESS                 METHOD

# only allow unix domain socket connections for now
local   all             all                                     trust
# IPv4 local connections:
# host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
# host    all             all             ::1/128                 trust
# replication is not used so all disable for now
# local   replication     all                                     trust
# host    replication     all             127.0.0.1/32            trust
# host    replication     all             ::1/128                 trust
